"""
Meta-Prompt Evolution — once a week, Claude rewrites its own classification
prompt from accumulated lessons and accuracy stats.

After the daily journal entry, the pipeline asks: has it been a week since the
last evolution (or seven days of lessons, for the very first one)? If so,
evolve_prompt() feeds the current prompt, every lesson learned from a mistake,
and accuracy broken down by category and direction to Sonnet, asks for an
improved prompt, validates it still formats, and versions it:
  - a file under docs/prompts/classification_prompt_v{N}.txt (never overwritten)
  - a row in the prompt_versions table

The classifier then loads the latest version at runtime (classifier.get_active_prompt).
"""
from __future__ import annotations

import asyncio
import logging
import string
from datetime import datetime, timedelta, timezone

import anthropic

from locus import config
from locus.memory import logger
from locus.markets.gamma import _infer_category

log = logging.getLogger(__name__)

PROMPTS_DIR = config.PROJECT_ROOT / "docs" / "prompts"

# Sample kwargs used to verify an evolved prompt still .format()s cleanly before
# we trust it. Must cover every placeholder classifier.classify() fills in.
_VALIDATION_KWARGS = dict(
    question="Will X happen by 2027?",
    threshold_line="",
    time_remaining="3 days",
    yes_price=0.5,
    headline="Some breaking news",
    source="rss",
    track_record="No resolved classifications yet.",
)

# Placeholders classifier.classify() fills in — every one must survive evolution
# or the runtime .format() blows up. Stored as bare field names (no braces, no
# format spec) so {yes_price:.3f} still counts as {yes_price}.
REQUIRED_PLACEHOLDERS = (
    "question",
    "yes_price",
    "time_remaining",
    "headline",
    "source",
    "track_record",
    "threshold_line",
)

# The JSON output contract is appended verbatim to every evolved prompt rather
# than generated by the model — otherwise a truncated model response can drop it
# and break downstream JSON parsing. Braces are doubled so the stored prompt
# still .format()s cleanly (they collapse to single braces at runtime).
REQUIRED_JSON_SUFFIX = '''

Respond with ONLY valid JSON:
{{
  "direction": "bullish" | "bearish" | "neutral",
  "materiality": <float 0.0 to 1.0>,
  "confidence": <float 0.5 to 1.0>,
  "time_horizon": "immediate" | "medium" | "long_term",
  "reasoning": "<string>"
}}
'''


def _parse_dt(value: str) -> datetime:
    """Parse a stored 'YYYY-MM-DD HH:MM:SS' timestamp as UTC."""
    dt = datetime.fromisoformat(value.replace(" ", "T"))
    return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt


def should_evolve(now: datetime | None = None) -> bool:
    """True when a prompt evolution is due.

    - If a prior version exists: due when PROMPT_EVOLUTION_INTERVAL_DAYS have
      passed since it was created.
    - If no version exists yet (first evolution): due once the oldest lesson is
      at least PROMPT_EVOLUTION_INTERVAL_DAYS old — i.e. a week of data to learn
      from. With no lessons at all there is nothing to improve, so not due.

    Disabled entirely via config.PROMPT_EVOLUTION_ENABLED.
    """
    if not config.PROMPT_EVOLUTION_ENABLED:
        return False
    now = now or datetime.now(timezone.utc)
    interval = timedelta(days=config.PROMPT_EVOLUTION_INTERVAL_DAYS)

    latest = logger.get_latest_prompt_version()
    if latest:
        return (now - _parse_dt(latest["created_at"])) >= interval

    earliest_lesson = logger.get_earliest_lesson_date()
    if not earliest_lesson:
        return False
    return (now - _parse_dt(earliest_lesson)) >= interval


def compute_accuracy_stats() -> dict:
    """Accuracy from graded classifications, broken down by category and
    direction. Returns {total, overall, by_category, by_direction} with
    percentages (0-100)."""
    rows = logger.get_classification_grades_with_meta()

    by_category: dict[str, list[int]] = {}
    by_direction: dict[str, list[int]] = {}
    for r in rows:
        cat = _infer_category(r.get("market_question") or "", [])
        direction = r.get("classification") or "neutral"
        by_category.setdefault(cat, []).append(r["correct"])
        by_direction.setdefault(direction, []).append(r["correct"])

    def _pct(values: list[int]) -> float:
        return round(sum(values) / len(values) * 100, 1) if values else 0.0

    return {
        "total": len(rows),
        "overall": _pct([r["correct"] for r in rows]),
        "by_category": {k: _pct(v) for k, v in by_category.items()},
        "by_direction": {k: _pct(v) for k, v in by_direction.items()},
    }


def build_meta_prompt(current_prompt: str, lessons: list[dict], stats: dict) -> str:
    """Construct the instruction sent to Sonnet to improve the prompt."""
    lesson_lines = "\n".join(f"- {l['lesson']}" for l in lessons) or "(none yet)"

    stat_parts = [f"{cat} {pct}%" for cat, pct in stats["by_category"].items()]
    stat_parts += [f"{d} {pct}%" for d, pct in stats["by_direction"].items()]
    stat_str = ", ".join(stat_parts) if stat_parts else "no graded data yet"

    return (
        "You are improving an AI trading agent's classification prompt. "
        "Here is the current prompt:\n\n"
        f"{current_prompt}\n\n"
        f"Here are {len(lessons)} lessons learned from mistakes:\n{lesson_lines}\n\n"
        f"Accuracy stats: {stat_str}.\n\n"
        "Improve the prompt to: 1) avoid the patterns that led to these mistakes, "
        "2) be more calibrated for categories with low accuracy. "
        "Do NOT include the final JSON output contract / 'Respond with ONLY valid "
        "JSON' block — that is appended automatically, so end your prompt with the "
        "classification instructions. "
        "You MUST keep every curly-brace template placeholder exactly as-is "
        "({question}, {threshold_line}, {yes_price}, {time_remaining}, {headline}, "
        "{source}, {track_record}) and must not introduce any new curly-brace "
        "tokens. Return ONLY the improved prompt text, nothing else."
    )


def _strip_fences(text: str) -> str:
    """Strip a wrapping Markdown code fence if the model added one."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    return text


def _placeholder_names(prompt: str) -> set[str]:
    """The set of {field} names a prompt references, ignoring format specs and
    escaped {{ }} braces. Raises ValueError on malformed braces."""
    names: set[str] = set()
    for _literal, field_name, _spec, _conv in string.Formatter().parse(prompt):
        if field_name:  # None for literal text, "" for positional {}
            names.add(field_name.split(".")[0].split("[")[0])
    return names


def validate_prompt(prompt: str) -> list[str]:
    """Return a list of human-readable reasons a candidate prompt is unusable;
    an empty list means it is valid. A prompt is usable only if it keeps every
    required placeholder, keeps the JSON output contract, and still .format()s
    cleanly with the real runtime kwargs (no stray/unknown braces)."""
    if not prompt or not prompt.strip():
        return ["prompt is empty"]

    problems: list[str] = []
    try:
        present = _placeholder_names(prompt)
    except ValueError as e:
        return [f"malformed format string (unbalanced braces?): {e}"]

    missing = [f"{{{name}}}" for name in REQUIRED_PLACEHOLDERS if name not in present]
    if missing:
        problems.append("missing required placeholders: " + ", ".join(missing))

    for field in ('"direction"', '"materiality"'):
        if field not in prompt:
            problems.append(f'JSON output contract missing the {field} field')

    try:
        prompt.format(**_VALIDATION_KWARGS)
    except (KeyError, IndexError, ValueError) as e:
        problems.append(f"prompt.format() failed: {type(e).__name__}: {e}")

    return problems


def prompt_is_valid(prompt: str) -> bool:
    """Boolean form of validate_prompt()."""
    return not validate_prompt(prompt)


# Tacked onto the meta-prompt on a retry, after a first attempt produced an
# unusable prompt — it spells out the contract more forcefully than build_meta_prompt.
_STRICT_RETRY_SYSTEM = (
    "You are editing a Python str.format() template. Output ONLY the raw template "
    "text: no markdown, no ``` code fences, no preamble, no commentary. You MUST "
    "keep every curly-brace placeholder exactly as written and introduce no new ones. "
    "The required placeholders are: {question}, {threshold_line}, {yes_price}, "
    "{time_remaining}, {headline}, {source}, {track_record}. The JSON output block "
    'must still contain the "direction" and "materiality" fields. A response that '
    "drops or renames any placeholder is unusable."
)


async def _generate_improved_prompt(meta_prompt: str, system: str | None = None) -> str:
    """Call Sonnet for the improved prompt (off the event loop). An optional
    system prompt is used to tighten the contract on retries."""
    def _call() -> str:
        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        kwargs = dict(
            model=config.SCORING_MODEL,
            max_tokens=4096,
            temperature=0.4,
            messages=[{"role": "user", "content": meta_prompt}],
        )
        if system:
            kwargs["system"] = system
        resp = client.messages.create(**kwargs)
        return resp.content[0].text.strip()

    return await asyncio.get_event_loop().run_in_executor(None, _call)


async def evolve_prompt() -> dict | None:
    """Evolve the classification prompt from accumulated lessons + accuracy.

    Returns a summary dict on success, or None when nothing was saved (the
    model's output failed validation, or generation errored)."""
    lessons = logger.get_all_lessons()
    stats = compute_accuracy_stats()
    current_prompt = _current_prompt()
    meta_prompt = build_meta_prompt(current_prompt, lessons, stats)

    max_attempts = max(1, config.EVOLVE_MAX_RETRIES)
    candidate = ""
    problems: list[str] = []
    for attempt in range(1, max_attempts + 1):
        # First attempt uses the plain meta-prompt; later ones add a stricter
        # system prompt that re-states the placeholder/JSON contract.
        system = _STRICT_RETRY_SYSTEM if attempt > 1 else None
        try:
            raw = await _generate_improved_prompt(meta_prompt, system=system)
        except Exception as e:
            log.warning(f"[meta_evolver] Prompt generation failed (attempt {attempt}): {e}")
            return None

        # The model writes the prompt body; the JSON output contract is appended
        # here so it survives even if the model truncates its response.
        candidate = _strip_fences(raw) + REQUIRED_JSON_SUFFIX
        problems = validate_prompt(candidate)
        if not problems:
            break

        log.warning(
            "[meta_evolver] Evolved prompt failed validation "
            f"(attempt {attempt}/{max_attempts}): {'; '.join(problems)}"
        )
        log.warning(
            "[meta_evolver] Generated prompt (first 500 chars):\n%s",
            candidate[:500],
        )
    else:
        log.warning(
            f"[meta_evolver] Evolved prompt still invalid after {max_attempts} "
            f"attempt(s); not saving. Last problems: {'; '.join(problems)}"
        )
        return None

    latest = logger.get_latest_prompt_version()
    version = (latest["version"] + 1) if latest else 1

    # Never overwrite: bump until the versioned file name is free, keeping the
    # DB version in lockstep with the file on disk.
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    path = PROMPTS_DIR / f"classification_prompt_v{version}.txt"
    while path.exists():
        version += 1
        path = PROMPTS_DIR / f"classification_prompt_v{version}.txt"
    path.write_text(candidate)

    logger.save_prompt_version(
        version=version,
        prompt_text=candidate,
        lessons_count=len(lessons),
        accuracy_at_creation=stats["overall"],
    )

    summary = {
        "version": version,
        "path": str(path),
        "lessons_count": len(lessons),
        "accuracy_at_creation": stats["overall"],
        "chars": len(candidate),
        "prev_chars": len(current_prompt),
    }
    log.info(
        f"[meta_evolver] Evolved classification prompt -> v{version} "
        f"({len(lessons)} lessons, accuracy {stats['overall']}%, "
        f"{summary['prev_chars']} -> {summary['chars']} chars)"
    )
    return summary


def evolve_prompt_sync() -> dict | None:
    """Blocking wrapper around evolve_prompt() for sync callers (the journal
    trigger runs in a thread-pool executor with no event loop)."""
    return asyncio.run(evolve_prompt())


def _current_prompt() -> str:
    """The prompt to improve upon — the active one (latest evolved or hardcoded).
    Imported lazily to avoid a circular import with the classifier."""
    from locus.core import classifier
    return classifier.get_active_prompt()
